# frozen_string_literal: true

require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'lib'
  t.libs << 'test'
  t.test_files = FileList['**/test/**/*_test.rb']
  t.warning = false
end

task :rubocop do
  sh 'bundle exec rubocop'
end

task check: %i[rubocop test]

task default: :test
