<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="TemplateMethod.fs" />
    <Compile Include="Strategy.fs" />
    <Compile Include="Observer.fs" />
    <Compile Include="Composite.fs" />
    <Compile Include="Iterator.fs" />
    <Compile Include="Command.fs" />
    <Compile Include="Adapter.fs" />
    <Compile Include="Proxy.fs" />
    <Compile Include="Decorator.fs" />
    <Compile Include="Singleton.fs" />
    <Compile Include="Factory.fs" />
    <Compile Include="Builder.fs" />
    <Compile Include="Interpreter.fs" />
  </ItemGroup>

</Project>
