name: CI Scala

on:
  push:
    branches: [main, develop]
    paths: ['apps/scala/design-pattern/**', '.github/workflows/ci-scala.yml']
  pull_request:
    branches: [main]
    paths: ['apps/scala/design-pattern/**', '.github/workflows/ci-scala.yml']

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/scala/design-pattern
    steps:
      - uses: actions/checkout@v4
      - uses: VirtusLab/scala-cli-setup@v1
      - run: scala-cli test .
